{
  "name": "zid-pf-error-handling-basics-02-try-catch",
  "version": "1.0.0",
  "description": "zid-pf-error-handling-basics-02-try-catch qualified challenge.",
  "main": "src/app.js",
  "directories": {
    "src": "src",
    "doc": "docs"
  },
  "scripts": {
    "docker:build": "docker image build . -t thinkful-ed/zid-pf-error-handling-basics-02-try-catch",
    "docker:run": "docker run --rm -it -p 3000:3000 thinkful-ed/zid-pf-error-handling-basics-02-try-catch",
    "docker:stop": "docker stop $(docker ps -q)",
    "docker:test": "docker run -t  thinkful-ed/zid-pf-error-handling-basics-02-try-catch npm test",
    "start:solution": "npm run -it docker:build && npm run docker:run",
    "test": "mocha test",
    "test:solution": "npm run docker:build && npm run docker:test"
  },
  "keywords": [],
  "author": "Thinkful.com",
  "license": "UNLICENSED",
  "devDependencies": {
    "chai": "^4.3.4",
    "mocha": "^8.3.2"
  }
}
